require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'audioexample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'

  target 'audioexampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'audioexample-tvOS' do
  # Pods for audioexample-tvOS

  target 'audioexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
